services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 사용자 비밀번호
      MYSQL_DATABASE: sampledb          # 초기 생성할 데이터베이스
      MYSQL_USER: user            # 사용자 이름
      MYSQL_PASSWORD: 1234    # 사용자 비밀번호
    volumes:
      - mariadb_docker_mariadb_data:/var/lib/mysql     # 데이터 볼륨 마운트
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mariadb_docker_mariadb_data:

