services:
  mariadb:
    # image: mariadb:latest
    # build:
    #   context: .
    #   dockerfile: mariadb.Dockerfile
    build:
      context: .
      dockerfile_inline: |
        # MariaDB 기본 이미지 사용
        FROM mariadb:latest

        # 필요한 패키지 설치
        RUN apt-get update -y && apt-get install -y nano vim sudo && rm -rf /var/lib/apt/lists/*

        # MariaDB 포트 노출
        EXPOSE 3306

        # MariaDB 실행
        CMD ["mysqld"]
    container_name: mariadb_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 사용자 비밀번호
      MYSQL_DATABASE: sampledb          # 초기 생성할 데이터베이스
      MYSQL_USER: user            # 사용자 이름
      MYSQL_PASSWORD: 1234    # 사용자 비밀번호
    volumes:
      - mariadb_docker_mariadb_data:/var/lib/mysql     # 데이터 볼륨 마운트
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mariadb_docker_mariadb_data:

